name: hairsalonhayyina
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/images/LoveYourSelf.jpg
    - lib/assets/images/haircare.jpg
    - lib/assets/images/skincare.jpg
    - lib/assets/images/bodycare.jpg
    - lib/assets/images/nailcare.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
